import { createHash } from "node:crypto";
import { hasCategoricalX, type FigureSpec } from "../schema.ts";
import { emitAltText } from "../alttext.ts";
import { emitClaimTests, CLAIM_WORDING } from "../claims.ts";
import { emitAnimation } from "./animate.ts";
import {
  emitBootstrap,
  emitLoad,
  emitMissingIntervalReport,
  needsMissingIntervalReport,
  emitPrepare,
  emitSmooth,
  emitSummarise,
} from "./data.ts";
import { emitDecoratePanel, emitHelpers, emitLegend } from "./decorate.ts";
import {
  emitAxisBreak,
  emitInset,
  emitLayers,
  emitRepeat,
  emitTable,
} from "./compose.ts";
import { emitDraw } from "./draw.ts";
import {
  emitAltTextConstants,
  emitDataFingerprint,
  emitInteractive,
  emitLatex,
} from "./outputs.ts";
import { pyList, pyOptStr, pyStr } from "./py.ts";
import {
  BAND_ALPHA,
  DIVERGING,
  FIGURE_SIZES,
  HATCHES,
  LINE_STYLES,
  MARKERS,
  PALETTE,
  PRESETS,
  RAW_ALPHA,
  RECEDED_ALPHA,
  SECOND_CHANNEL_THRESHOLD,
  SEQUENTIAL,
  TOOL_VERSION,
  VENUE_RULES,
} from "./theme.ts";

export { TOOL_VERSION } from "./theme.ts";

/** Width the figure will occupy on the page, which the venue can override. */
export function targetWidth(spec: FigureSpec): number {
  const venue = VENUE_RULES[spec.style.venue];
  return spec.output.size === "single_column" ? venue.single : venue.double;
}

function figureSize(spec: FigureSpec): [number, number] {
  const [defaultWidth, defaultHeight] = FIGURE_SIZES[spec.output.size];
  const width = targetWidth(spec);
  const height = Number(((defaultHeight * width) / defaultWidth).toFixed(3));
  if (!spec.facet) return [width, height];
  return [width, height];
}

function emitPreamble(spec: FigureSpec, out: string[]): void {
  const preset = PRESETS[spec.style.preset];
  const venue = VENUE_RULES[spec.style.venue];
  const [width, height] = figureSize(spec);
  const specJson = JSON.stringify(spec);
  const specHash = createHash("sha256").update(specJson).digest("hex").slice(0, 16);

  out.push(
    "# Generated by GraphUnslopify from a FigureSpec.",
    `# tool version ${TOOL_VERSION}, spec sha256:${specHash}`,
    "# Every number below is a presentation decision owned by the generator.",
    "# Change the spec and regenerate rather than editing this file.",
    "#",
    "# The spec is embedded in the exported files' metadata, so a reader can",
    "# recover exactly what produced this figure. DISCLOSURE is ready to paste",
    "# into a methods section.",
    "import hashlib",
    "import math",
    "",
    "import matplotlib",
    "",
    'matplotlib.use("Agg")',
    "",
    "import matplotlib.pyplot as plt",
    "import matplotlib.ticker as mticker",
    "import numpy as np",
    "import pandas as pd",
  );
  if (spec.x.temporal) out.push("import matplotlib.dates as mdates");
  if (spec.animate) {
    out.push(
      "from matplotlib.animation import FuncAnimation, FFMpegWriter, PillowWriter",
    );
  }
  out.push("");

  out.push("RC_PARAMS = {");
  for (const [key, value] of Object.entries(preset.rc)) out.push(`    ${pyStr(key)}: ${value},`);
  out.push("}", "");

  out.push(`FIGSIZE = (${width}, ${height})`);
  out.push(`TARGET_WIDTH_IN = ${width}`);
  out.push(`MIN_TEXT_PT = ${venue.min_pt}`);
  out.push(`PALETTE = ${pyList(PALETTE)}`);
  out.push(`DIVERGING_MAP = mcolors.LinearSegmentedColormap.from_list("gu_diverging", ${pyList(DIVERGING)})`);
  out.push(`SEQUENTIAL_MAP = ${pyStr(SEQUENTIAL)}`);
  out.push(`RECEDED_ALPHA = ${RECEDED_ALPHA}`);
  out.push(`BAND_ALPHA = ${BAND_ALPHA}`);
  out.push(`RAW_ALPHA = ${RAW_ALPHA}`);
  out.push(`ANNOTATION_PT = ${preset.annotation_pt}`);
  out.push(`PANEL_LETTER_PT = ${preset.panel_letter_pt}`);
  out.push(`SECOND_CHANNEL_THRESHOLD = ${SECOND_CHANNEL_THRESHOLD}`);
  if (spec.kind === "scatter") out.push(`MARKERS = ${pyList(MARKERS)}`);
  else if (spec.kind === "line") out.push(`LINE_STYLES = ${pyList(LINE_STYLES)}`);
  else if (spec.kind === "bar") out.push(`HATCHES = ${pyList(HATCHES)}`);
  out.push("");

  out.push(`DATA_PATH = ${pyStr(spec.data.path)}`);
  out.push(`X_FIELD = ${pyStr(spec.x.field)}`);
  out.push(`X_TEMPORAL = ${spec.x.temporal ? "True" : "False"}`);
  out.push(`Y_FIELD = ${pyStr(spec.kind === "heatmap" ? spec.y.field : spec.y.field)}`);
  if (spec.kind === "heatmap") {
    out.push(`VALUE_FIELD = ${pyStr(spec.value)}`);
    out.push(`VALUE_LABEL = ${pyStr(spec.value_label)}`);
  }
  out.push(`GROUP = ${pyOptStr(spec.group)}`);
  out.push(`SERIES_ORDER = ${spec.series_order ? pyList(spec.series_order) : "None"}`);
  out.push(`EMPHASIS = ${pyOptStr(spec.emphasis?.series)}`);
  out.push(`SERIES_COUNT = ${spec.series_order ? spec.series_order.length : 1}`);
  out.push(`PALETTE_LOCK = ${pyOptStr(spec.palette_lock)}`);
  if (spec.layers?.length) out.push('LAYER_COLOURS = ["#767676", "#404040", "#a0a0a0"]');
  if (spec.inset) out.push('INSET_EDGE = "#5a5a5a"');
  if (spec.repeat) {
    out.push(`REPEAT_FIELDS = ${pyList(spec.repeat.fields)}`);
    out.push(`REPEAT_COLUMNS = ${spec.repeat.columns}`);
  }
  if (spec.kind === "table") {
    out.push(`HIGHLIGHT = ${pyStr(spec.highlight)}`);
    out.push(`HIGHER_IS_BETTER = ${spec.higher_is_better ? "True" : "False"}`);
  }
  out.push("LOCKED = None");
  if (hasCategoricalX(spec)) {
    const order = "category_order" in spec ? spec.category_order : undefined;
    out.push(`CATEGORY_ORDER = ${order ? pyList(order) : "None"}`);
  }
  if (spec.transform?.baseline) out.push(`BASELINE_SERIES = ${pyStr(spec.transform.baseline)}`);
  if (spec.kind === "line" && spec.y2) {
    out.push(`Y2_FIELD = ${pyStr(spec.y2.field)}`);
    const label = spec.y2.unit ? `${spec.y2.label} (${spec.y2.unit})` : spec.y2.label;
    out.push(`Y2_LABEL = ${pyStr(label)}`);
    out.push(`Y2_JUSTIFICATION = ${pyStr(spec.y2.justification)}`);
  }
  if (spec.kind === "box" || spec.kind === "violin") out.push("POINT_JITTER_SEED = 20260902");
  if ("uncertainty" in spec && spec.uncertainty) {
    out.push(`CI_LEVEL = ${spec.uncertainty.level}`);
    out.push("BOOTSTRAP_SEED = 20260902");
    out.push("BOOTSTRAP_DRAWS = 2000");
  }
  if (spec.kind === "bar" && spec.significance) {
    out.push(`SIGNIFICANCE_PAIRS = ${pyList(spec.significance.pairs.map((p) => [...p]))}`);
    out.push(`SIGNIFICANCE_ALPHA = ${spec.significance.alpha}`);
    if (!("uncertainty" in spec && spec.uncertainty)) {
      out.push("BOOTSTRAP_SEED = 20260902", "BOOTSTRAP_DRAWS = 2000");
    }
  }
  if (spec.annotate?.length) {
    const notes = spec.annotate.map((note) => ({
      at: typeof note.at === "string" ? note.at : note.at.x,
      series: note.series ?? null,
      text: note.text,
    }));
    out.push("ANNOTATIONS = [");
    for (const note of notes) {
      out.push(
        `    {"at": ${typeof note.at === "string" ? pyStr(note.at) : note.at}, ` +
          `"series": ${note.series === null ? "None" : pyStr(note.series)}, ` +
          `"text": ${pyStr(note.text)}},`,
      );
    }
    out.push("]");
  }
  if (spec.facet) {
    out.push(`FACET_BY = ${pyStr(spec.facet.by)}`);
    out.push(`FACET_COLUMNS = ${spec.facet.columns}`);
    out.push(`SHARE_X = ${spec.facet.share_x ? "True" : "False"}`);
    out.push(`SHARE_Y = ${spec.facet.share_y ? "True" : "False"}`);
  }
  if (spec.animate) {
    out.push(`ANIMATE_DURATION = ${spec.animate.duration_s}`);
    out.push(`ANIMATE_FPS = ${spec.animate.fps}`);
    out.push(`ANIMATE_EASING = ${pyStr(spec.animate.easing)}`);
    out.push(`ANIMATE_STAGGER = ${spec.animate.stagger_s}`);
    out.push(`ANIMATE_HOLD = ${spec.animate.hold_s}`);
    out.push("ANIMATION_DPI = 160");
  }
  out.push(`STEM = ${pyStr(spec.output.stem)}`);
  out.push(`FORMATS = ${pyList(spec.output.formats)}`);
  out.push(`DPI = ${spec.output.dpi}`);
  out.push(`TOOL = "GraphUnslopify ${TOOL_VERSION}"`);
  out.push(`SPEC_HASH = ${pyStr(specHash)}`);
  out.push(`SPEC_JSON = ${pyStr(specJson)}`);
  const axisLabel = (label: string, unit?: string) => (unit ? `${label} (${unit})` : label);
  out.push(`X_AXIS_LABEL = ${pyStr(axisLabel(spec.x.label, spec.x.unit))}`);
  out.push(`Y_AXIS_LABEL = ${pyStr(axisLabel(spec.y.label, spec.y.unit))}`);
  out.push(`FIGURE_TITLE = ${pyOptStr(spec.title)}`);
  emitAltTextConstants(spec, out);

  if (spec.claims?.length) {
    out.push("CLAIMS = [");
    for (const claim of spec.claims) {
      out.push(
        `    {"kind": ${pyStr(claim.kind)}, "subject": ${pyStr(claim.subject)}, ` +
          `"reference": ${pyOptStr(claim.reference)}, ` +
          `"tolerance": ${claim.tolerance === undefined ? "None" : claim.tolerance}, ` +
          `"wording": ${pyStr(CLAIM_WORDING[claim.kind])}},`,
      );
    }
    out.push("]");
  } else {
    out.push("CLAIMS = []");
  }

  out.push("DATA_HASH = \"unknown\"");
  out.push("ALT_TEXT = \"\"");
  out.push(
    "DISCLOSURE = (",
    '    f"This figure was produced by {TOOL} from a declarative figure "',
    '    f"specification (sha256:{SPEC_HASH}); the plotting code was generated, "',
    '    f"the underlying data were not."',
    ")",
    "",
  );
}

function emitMain(spec: FigureSpec, out: string[]): void {
  const warnsDuplicates =
    (spec.kind === "line" || spec.kind === "bar") && spec.aggregation === "none";

  if (warnsDuplicates) {
    out.push(
      "",
      "def warn_duplicates(df):",
      "    # Whether x repeats is not knowable from the spec, so it is checked here.",
      "    keys = [X_FIELD] + ([GROUP] if GROUP is not None else [])",
      "    if df.duplicated(subset=keys).any():",
      '        print("warning: repeated x values per series are drawn on top of each other.")',
      '        print("         set aggregation to mean or median to summarise them.")',
      "",
    );
  }

  out.push(
    "",
    "def metadata_for(fmt):",
    "    # Embedding the spec means a reviewer can recover what produced the figure.",
    "    stamp = f\"{TOOL} spec:{SPEC_HASH} data:{DATA_HASH}\"",
    '    if fmt == "png":',
    '        return {"Software": stamp, "Description": SPEC_JSON, "Comment": ALT_TEXT}',
    '    if fmt == "svg":',
    '        return {"Creator": stamp, "Description": ALT_TEXT, "Title": SPEC_HASH}',
    '    return {"Creator": stamp, "Subject": SPEC_JSON, "Keywords": SPEC_HASH}',
    "",
    "",
    "def check(fig):",
    "    # Optional. Install graphunslopify for readability and colour checks.",
    "    try:",
    "        from graphunslopify import inspect_figure",
    "    except ImportError:",
    '        print("graphunslopify not installed, skipping figure checks")',
    "        return True",
    "    report = inspect_figure(fig, target_width_in=TARGET_WIDTH_IN, min_text_pt=MIN_TEXT_PT)",
    "    print(report)",
    "    return report.ok",
    "",
    "",
    "def panels(df):",
    '    """One entry per panel. Without faceting that is the whole frame."""',
  );
  if (spec.facet) {
    out.push(
      "    names = list(dict.fromkeys(df[FACET_BY].dropna().tolist()))",
      "    return [(name, df[df[FACET_BY] == name]) for name in names]",
    );
  } else {
    out.push("    return [(None, df)]");
  }
  if (!spec.facet) out.push("", "", "SHARE_X = False", "SHARE_Y = False", "FACET_COLUMNS = 1");

  const letters = spec.facet?.panel_letters ?? false;
  out.push(
    "",
    "",
    "def main():",
    "    global DATA_HASH, ALT_TEXT",
    "    DATA_HASH = data_fingerprint()",
    "    df = prepare(load())",
  );

  if (spec.kind === "table") {
    out.push(
      "    table = build_table(df)",
      "    markdown, winners = write_table(table)",
      "    render_table_image(table, winners)",
      "    ALT_TEXT = ENCODING_SENTENCE",
      "    print(DISCLOSURE)",
      '    print(f"data sha256:{DATA_HASH}")',
      "",
      "",
      'if __name__ == "__main__":',
      "    main()",
    );
    return;
  }
  if (warnsDuplicates) out.push("    warn_duplicates(df)");
  out.push(
    "    if PALETTE_LOCK is not None and GROUP is not None:",
    "        globals()[\"LOCKED\"] = locked_appearance(",
    "            SERIES_ORDER if SERIES_ORDER is not None else sorted(df[GROUP].dropna().unique(), key=str)",
    "        )",
    spec.repeat ? "    blocks = repeated_panels(df)" : "    blocks = panels(df)",
    spec.repeat
      ? "    columns = min(REPEAT_COLUMNS, len(blocks))"
      : "    columns = min(FACET_COLUMNS, len(blocks)) if len(blocks) > 1 else 1",
    "    rows = math.ceil(len(blocks) / columns)",
    "",
    "    with plt.rc_context(RC_PARAMS):",
  );

  if (spec.axis_break) {
    // A cut axis is two stacked axes, so it cannot go through the panel loop.
    out.push(
      "        fig = plt.figure(figsize=(FIGSIZE[0], FIGSIZE[1] * 1.25))",
      "        upper, lower = draw_with_break(fig, df)",
      "        flat = [lower]",
      "        blocks = [(None, df)]",
      "        decorate_panel(lower, df, None, True, True)",
      "        decorate_panel(upper, df, None, False, True)",
      "        upper.set_ylabel(None)",
      "        add_legend(fig, upper, df)",
      "        legend = lower.get_legend()",
      "        if legend is not None:",
      "            legend.remove()",
    );
    emitSaveBlock(spec, out);
    return;
  }

  out.push(
    "        fig, axes = plt.subplots(",
    "            rows,",
    "            columns,",
    "            figsize=(FIGSIZE[0], FIGSIZE[1] * rows) if rows > 1 else FIGSIZE,",
    `            sharex=${spec.facet?.share_x ? "True" : "False"},`,
    `            sharey=${spec.facet?.share_y ? "True" : "False"},`,
    "            squeeze=False,",
    "        )",
    "        flat = list(axes.flat)",
    "        for index, (name, block) in enumerate(blocks):",
    "            ax = flat[index]",
    ...(needsMissingIntervalReport(spec) ? ['            globals()["PANEL_KEY"] = index'] : []),
    spec.repeat
      ? '            globals()["Y_FIELD"] = name'
      : "",
    ...(spec.repeat ? ['            letter_override = pretty(name)'] : []),
    "            draw_panel(ax, block)",
    spec.layers?.length ? "            draw_layers(ax, block)" : "",
    spec.inset ? "            add_inset(ax, block)" : "",
    spec.repeat
      ? '            letter = f"({chr(ord(chr(97)) + index)}) {letter_override}"'
      : letters
        ? '            letter = f"({chr(ord(chr(97)) + index)}) {name}" if name is not None else None'
        : "            letter = str(name) if name is not None else None",
    "            show_x = (index // columns) == rows - 1 or not SHARE_X",
    "            show_y = (index % columns) == 0 or not SHARE_Y",
    "            decorate_panel(ax, block, letter, show_x, show_y)",
    ...(spec.repeat
      ? [
          "            # Each repeated panel is a different metric, so the spec's",
          "            # own y label and unit do not apply to any of them.",
          "            ax.set_ylabel(pretty(name))",
          "            ax.set_title(None)",
        ]
      : []),
    "            # One legend for the whole figure; repeating it wastes panel space.",
    "            if index == 0:",
    "                add_legend(fig, ax, block)",
    "        for spare in flat[len(blocks) :]:",
    "            spare.set_visible(False)",
    "",
  );

  if (spec.title) {
    out.push(
      "        if len(blocks) > 1:",
      `            fig.suptitle(${pyStr(spec.title)})`,
      "        else:",
      `            flat[0].set_title(${pyStr(spec.title)})`,
    );
  }

  const outsideLegend =
    spec.group !== undefined &&
    spec.legend.show &&
    spec.legend.style === "box" &&
    (spec.legend.position === "outside_right" || spec.legend.position === "outside_bottom");

  out.push(
    outsideLegend
      ? "        # tight_layout is skipped: it fights a legend anchored outside the axes."
      : "        fig.tight_layout()",
  );
  if (spec.kind === "line" && spec.y2) {
    out.push('        print(f"dual axis in use. Justification: {Y2_JUSTIFICATION}")');
  }
  emitSaveBlock(spec, out);
}

function emitSaveBlock(spec: FigureSpec, out: string[]): void {
  out.push(
    "        check(fig)",
    "        summary = summarise(df) if GROUP is not None else df",
    "        claims_hold = verify_claims(summary)",
    "        for claim in CLAIMS:",
    '            verdict, _ = check_claim(summary, claim)',
    '            claim["_verdict"] = verdict',
    '            claim["_overlap"] = _interval_overlap(summary, claim["subject"], claim.get("reference"))',
    "        description = alt_text(summary)",
    "        if AUTHOR_CONTEXT:",
    '            description = f"{description} {AUTHOR_CONTEXT}"',
    '        print(f"alt text: {description}")',
    "        for fmt in FORMATS:",
    '            path = f"{STEM}.{fmt}"',
    "            meta = metadata_for(fmt)",
    "            fig.savefig(path, bbox_inches=\"tight\", metadata=meta, **({\"dpi\": DPI} if fmt == \"png\" else {}))",
    '            print(f"wrote {path}")',
  );
  if (spec.animate) {
    out.push(
      "        if len(blocks) == 1:",
      "            write_animation(fig, flat[0], blocks[0][1])",
      "        else:",
      '            print("animation is skipped for faceted figures")',
    );
  }
  out.push(
    "    plt.close(fig)",
    spec.output.latex ? "    write_latex(description)" : "",
    spec.output.interactive
      ? "    write_interactive(df)"
      : "",
    needsMissingIntervalReport(spec) ? "    report_missing_interval()" : "",
    "    print(DISCLOSURE)",
    '    print(f"data sha256:{DATA_HASH}")',
    "    if not claims_hold:",
    '        print("at least one claim failed. The caption must not assert it.")',
    "",
    "",
    'if __name__ == "__main__":',
    "    main()",
  );
}

export function emitPython(spec: FigureSpec): string {
  const out: string[] = [];
  emitPreamble(spec, out);
  emitLoad(spec, out);
  emitPrepare(spec, out);
  emitBootstrap(spec, out);
  emitMissingIntervalReport(spec, out);
  emitSummarise(spec, out);
  emitSmooth(spec, out);
  emitHelpers(spec, out);
  if (spec.kind === "table") {
    emitTable(spec, out);
  } else {
    emitDraw(spec, out);
    emitLayers(spec, out);
    emitInset(spec, out);
    emitAxisBreak(spec, out);
    emitRepeat(spec, out);
  }
  emitDecoratePanel(spec, out);
  emitLegend(spec, out);
  emitDataFingerprint(out);
  emitClaimTests(spec.claims ?? [], out);
  emitAltText(spec, out);
  emitLatex(spec, out);
  emitInteractive(spec, out);
  emitAnimation(spec, out);
  emitMain(spec, out);

  const source = out.join("\n").replace(/\n{3,}/g, "\n\n\n") + "\n";
  return source.replace(
    "import matplotlib.pyplot as plt",
    "import matplotlib.colors as mcolors\nimport matplotlib.pyplot as plt",
  );
}
