/**
 * Rebuilds pipeline/queue.md from the specs on disk.
 *
 * The queue is an index, not a source of truth. Each spec carries its own
 * status and priority in frontmatter, so a hand-edited queue would be one more
 * thing to disagree with the specs it lists.
 *
 *   node --experimental-strip-types scripts/queue.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type Spec = { id: string; slug: string; status: string; priority: string; title: string; file: string };

const ORDER = ["needs_rework", "ready", "in_progress", "blocked"];
const RANK = ["P0", "P1", "P2"];

function parse(dir: string, name: string): Spec | undefined {
  const text = readFileSync(join(dir, name), "utf8");
  const block = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
  const front = block?.[1];
  if (!front) return undefined;
  const field = (key: string) =>
    new RegExp(`^${key}:\s*(.+)$`, "m").exec(front)?.[1]?.trim() ?? "";
  return {
    id: field("id"),
    slug: field("slug"),
    status: field("status") || "ready",
    priority: field("priority") || "P2",
    title: field("title"),
    file: name,
  };
}

const specs: Spec[] = [];
for (const dir of ["pipeline/specs", "pipeline/done"]) {
  let names: string[];
  try {
    names = readdirSync(dir).filter((n) => n.endsWith(".md"));
  } catch {
    continue;
  }
  for (const name of names) {
    const spec = parse(dir, name);
    if (spec) specs.push({ ...spec, status: dir.endsWith("done") ? "done" : spec.status });
  }
}

const rank = (s: Spec) => {
  const byStatus = ORDER.indexOf(s.status);
  return [byStatus < 0 ? ORDER.length : byStatus, RANK.indexOf(s.priority), s.id];
};
specs.sort((a, b) => String(rank(a)).localeCompare(String(rank(b))));

const open = specs.filter((s) => s.status !== "done");
const shipped = specs.filter((s) => s.status === "done");

const row = (s: Spec) => `| ${s.id} | ${s.priority} | ${s.status} | ${s.title} | \`${s.file}\` |`;
const lines = [
  "# Queue",
  "",
  "Generated by `npm run queue`. Edit the spec frontmatter, not this file.",
  "",
  `Open: ${open.length}. Shipped: ${shipped.length}.`,
  "",
  "| id | pri | status | title | file |",
  "| --- | --- | --- | --- | --- |",
  ...open.map(row),
];
if (shipped.length) {
  lines.push("", "## Shipped", "", "| id | pri | status | title | file |", "| --- | --- | --- | --- | --- |", ...shipped.map(row));
}
writeFileSync("pipeline/queue.md", lines.join("\n") + "\n");

const next = open.find((s) => s.status === "needs_rework") ?? open.find((s) => s.status === "ready");
console.log(`${open.length} open, ${shipped.length} shipped`);
console.log(next ? `next: ${next.id} ${next.slug} (${next.status}, ${next.priority})` : "next: nothing ready");
