import { createHash } from "node:crypto";
import type { AxisSpec, FigureSpec } from "./schema.ts";

/**
 * FigureSpec to runnable matplotlib.
 *
 * Every presentation number lives here. The spec never carries a line width, a
 * colour, or a font size, so two figures built from two specs still agree with
 * each other. Output is deterministic: the same spec emits byte-identical
 * Python, which is what makes the generated script reviewable in a diff.
 */

/** Okabe-Ito, minus the yellow, which is unreadable on white. */
const PALETTE = [
  "#0072B2",
  "#D55E00",
  "#009E73",
  "#CC79A7",
  "#E69F00",
  "#56B4E9",
  "#8C564B",
  "#000000",
];

/** Recessive series keep their hue and lose salience, so they stay tellable apart. */
const RECEDED_ALPHA = 0.4;

/**
 * Past this many series, colour alone stops being enough. A second channel
 * keeps the figure readable in greyscale and for a reader with a colour vision
 * deficiency, which is roughly one man in twelve.
 *
 * Two, not four. Okabe-Ito is colourblind-safe but not greyscale-safe: its
 * adjacent colours sit within 0.06 relative luminance of each other, so three
 * of them merge in a black and white print. The render-time checker flags that,
 * and there is no spec knob to fix it, so the emitter has to.
 */
const SECOND_CHANNEL_THRESHOLD = 2;
const LINE_STYLES = ["-", "--", "-.", ":"];
const MARKERS = ["o", "s", "^", "D", "v", "P", "X", "*"];

export const TOOL_VERSION = "0.3.0";

const FIGURE_SIZES = {
  single_column: [3.4, 2.6],
  double_column: [7.0, 4.2],
} as const;

const PRESETS = {
  paper: {
    rc: {
      "font.size": 9,
      "axes.labelsize": 9,
      "axes.titlesize": 9,
      "xtick.labelsize": 8,
      "ytick.labelsize": 8,
      "legend.fontsize": 8,
      "axes.linewidth": 0.8,
      "xtick.major.width": 0.8,
      "ytick.major.width": 0.8,
    },
    line: { base: 1.4, emphasis: 2.2, muted: 1.0 },
    marker: { base: 18, emphasis: 30, muted: 12 },
  },
  paper_compact: {
    rc: {
      "font.size": 8,
      "axes.labelsize": 8,
      "axes.titlesize": 8,
      "xtick.labelsize": 7,
      "ytick.labelsize": 7,
      "legend.fontsize": 7,
      "axes.linewidth": 0.7,
      "xtick.major.width": 0.7,
      "ytick.major.width": 0.7,
    },
    line: { base: 1.2, emphasis: 1.9, muted: 0.9 },
    marker: { base: 14, emphasis: 24, muted: 10 },
  },
} as const;

const LEGEND_LOCATIONS = {
  best: 'loc="best"',
  upper_left: 'loc="upper left"',
  upper_right: 'loc="upper right"',
  lower_left: 'loc="lower left"',
  lower_right: 'loc="lower right"',
  outside_right: 'loc="center left", bbox_to_anchor=(1.02, 0.5)',
  outside_bottom: 'loc="upper center", bbox_to_anchor=(0.5, -0.18)',
} as const;

const READERS = {
  csv: "read_csv",
  parquet: "read_parquet",
  json: "read_json",
} as const;

/** JSON string escaping is a subset of Python's, so this is safe for labels. */
function pyStr(value: string): string {
  return JSON.stringify(value);
}

function pyOptStr(value: string | undefined): string {
  return value === undefined ? "None" : pyStr(value);
}

function pyList(values: readonly (string | number)[]): string {
  return `[${values.map((v) => (typeof v === "string" ? pyStr(v) : String(v))).join(", ")}]`;
}

function axisLabel(axis: AxisSpec): string {
  return axis.unit ? `${axis.label} (${axis.unit})` : axis.label;
}

/**
 * A horizontal bar chart draws the category field up the vertical axis, so the
 * spec's x and y land on the opposite matplotlib axes from the ones they name.
 */
function plotAxis(spec: FigureSpec, specAxis: "x" | "y"): "x" | "y" {
  if (spec.kind === "bar" && spec.orientation === "horizontal") {
    return specAxis === "x" ? "y" : "x";
  }
  return specAxis;
}

/** For a bar chart the spec's x is a category on an index, whatever the orientation. */
function isCategorical(spec: FigureSpec, specAxis: "x" | "y"): boolean {
  return spec.kind === "bar" && specAxis === "x";
}

function emitHeader(spec: FigureSpec, out: string[]): void {
  const preset = PRESETS[spec.style.preset];
  const [width, height] = FIGURE_SIZES[spec.output.size];

  const specJson = JSON.stringify(spec);
  const specHash = createHash("sha256").update(specJson).digest("hex").slice(0, 16);

  out.push(
    "# Generated by GraphUnslopify from a FigureSpec.",
    `# tool version ${TOOL_VERSION}, spec sha256:${specHash}`,
    "# Every number below is a presentation decision owned by the generator.",
    "# Change the spec and regenerate rather than editing this file.",
    "#",
    "# The spec is embedded in the exported files' metadata, so any reader can",
    "# recover exactly what produced this figure. DISCLOSURE below is ready to",
    "# paste into a methods section.",
    "import matplotlib",
    "",
    'matplotlib.use("Agg")',
    "",
    "import matplotlib.pyplot as plt",
  );
  if (spec.kind === "bar") out.push("import numpy as np");
  else if (spec.kind === "scatter" && spec.trendline === "linear") out.push("import numpy as np");
  out.push("import pandas as pd", "");

  out.push("RC_PARAMS = {");
  for (const [key, value] of Object.entries(preset.rc)) out.push(`    ${pyStr(key)}: ${value},`);
  out.push("}", "");

  out.push(`FIGSIZE = (${width}, ${height})`);
  out.push(`PALETTE = ${pyList(PALETTE)}`);
  out.push(`RECEDED_ALPHA = ${RECEDED_ALPHA}`);
  out.push(`SECOND_CHANNEL_THRESHOLD = ${SECOND_CHANNEL_THRESHOLD}`);
  out.push(spec.kind === "scatter" ? `MARKERS = ${pyList(MARKERS)}` : `LINE_STYLES = ${pyList(LINE_STYLES)}`);
  out.push("");

  out.push(`DATA_PATH = ${pyStr(spec.data.path)}`);
  out.push(`X_FIELD = ${pyStr(spec.x.field)}`);
  out.push(`Y_FIELD = ${pyStr(spec.y.field)}`);
  if (spec.group) out.push(`GROUP = ${pyStr(spec.group)}`);
  if (spec.group) out.push(`SERIES_ORDER = ${spec.series_order ? pyList(spec.series_order) : "None"}`);
  if (spec.group) out.push(`EMPHASIS = ${pyOptStr(spec.emphasis?.series)}`);
  out.push(`STEM = ${pyStr(spec.output.stem)}`);
  out.push(`FORMATS = ${pyList(spec.output.formats)}`);
  out.push(`DPI = ${spec.output.dpi}`, "");
  out.push(`TOOL = "GraphUnslopify ${TOOL_VERSION}"`);
  out.push(`SPEC_HASH = ${pyStr(specHash)}`);
  out.push(`SPEC_JSON = ${pyStr(specJson)}`);
  out.push(
    "DISCLOSURE = (",
    '    f"This figure was produced by {TOOL} from a declarative figure "',
    '    f"specification (sha256:{SPEC_HASH}); the plotting code was generated, "',
    '    f"the underlying data were not."',
    ")",
    "",
  );
}

function emitSeriesHelpers(spec: FigureSpec, out: string[]): void {
  if (!spec.group) return;
  const preset = PRESETS[spec.style.preset];
  const sizes = spec.kind === "scatter" ? preset.marker : preset.line;
  const key = spec.kind === "scatter" ? "size" : "width";
  const scatter = spec.kind === "scatter";
  const channelConst = scatter ? "MARKERS" : "LINE_STYLES";
  const channelKey = scatter ? "marker" : "linestyle";
  const defaultChannel = scatter ? pyStr("o") : pyStr("-");

  out.push(
    "",
    "def series_names(frame):",
    "    if SERIES_ORDER is not None:",
    "        return list(SERIES_ORDER)",
    "    return sorted(frame[GROUP].dropna().unique().tolist(), key=str)",
    "",
    "",
    "def series_style(name, index, total):",
    "    colour = PALETTE[index % len(PALETTE)]",
    "    # Colour alone stops working past a handful of series, so add a second channel.",
    `    channel = ${channelConst}[index % len(${channelConst})] if total > SECOND_CHANNEL_THRESHOLD else ${defaultChannel}`,
    "    if name == EMPHASIS:",
    "        # The series being argued for reads as the plain form, not a dashed one.",
    `        channel = ${defaultChannel}`,
    "    if EMPHASIS is None:",
    `        style = {"colour": colour, ${pyStr(key)}: ${sizes.base}, "alpha": 1.0, "zorder": 2}`,
    "    elif name == EMPHASIS:",
    `        style = {"colour": colour, ${pyStr(key)}: ${sizes.emphasis}, "alpha": 1.0, "zorder": 3}`,
    "    else:",
    `        style = {"colour": colour, ${pyStr(key)}: ${sizes.muted}, "alpha": RECEDED_ALPHA, "zorder": 1}`,
    `    style[${pyStr(channelKey)}] = channel`,
    "    return style",
    "",
  );
}

function emitLoad(spec: FigureSpec, out: string[]): void {
  out.push("", "def load():", `    return pd.${READERS[spec.data.format]}(DATA_PATH)`, "");
}

/** Collapsing repeats needs the data, so this check runs where the data is. */
function emitDuplicateWarning(spec: FigureSpec, out: string[]): void {
  out.push(
    "",
    "def warn_duplicates(df):",
    `    keys = [X_FIELD${spec.group ? ", GROUP" : ""}]`,
    "    if df.duplicated(subset=keys).any():",
    '        print("warning: repeated x values per series are drawn on top of each other.")',
    '        print("         set aggregation to mean or median to summarise them.")',
    "",
  );
}

function emitAggregate(aggregation: string, spec: FigureSpec, out: string[]): void {
  out.push("", "def aggregate(df):");
  if (aggregation === "none") {
    out.push("    return df");
  } else {
    out.push(
      `    keys = [X_FIELD${spec.group ? ", GROUP" : ""}]`,
      "    # sort=False keeps the file's category order instead of an alphabetical one.",
      `    return df.groupby(keys, as_index=False, sort=False)[Y_FIELD].${aggregation}()`,
    );
  }
  out.push("");
}

function emitTrendline(out: string[]): void {
  out.push(
    "",
    "def add_trendline(ax, xs, ys, colour):",
    "    x = np.asarray(xs, dtype=float)",
    "    y = np.asarray(ys, dtype=float)",
    "    valid = np.isfinite(x) & np.isfinite(y)",
    "    if valid.sum() < 2:",
    "        return",
    "    slope, intercept = np.polyfit(x[valid], y[valid], 1)",
    "    line = np.linspace(x[valid].min(), x[valid].max(), 100)",
    '    ax.plot(line, slope * line + intercept, color=colour, linewidth=1.0, linestyle="--", zorder=1)',
    "",
  );
}

function emitLineDraw(spec: FigureSpec & { kind: "line" }, out: string[]): void {
  const preset = PRESETS[spec.style.preset];
  out.push("", "def draw(ax, df):", "    df = aggregate(df)");
  if (spec.group) {
    out.push(
      "    names = series_names(df)",
      "    for index, name in enumerate(names):",
      "        frame = df[df[GROUP] == name]",
    );
    if (spec.sort_x) out.push("        frame = frame.sort_values(X_FIELD)");
    out.push(
      "        style = series_style(name, index, len(names))",
      "        ax.plot(",
      "            frame[X_FIELD],",
      "            frame[Y_FIELD],",
      "            label=str(name),",
      '            color=style["colour"],',
      '            linewidth=style["width"],',
      '            alpha=style["alpha"],',
      '            zorder=style["zorder"],',
      '            linestyle=style["linestyle"],',
    );
    if (spec.marker) out.push('            marker="o",');
    out.push("        )");
  } else {
    out.push("    frame = df");
    if (spec.sort_x) out.push("    frame = frame.sort_values(X_FIELD)");
    out.push(
      "    ax.plot(",
      "        frame[X_FIELD],",
      "        frame[Y_FIELD],",
      "        color=PALETTE[0],",
      `        linewidth=${preset.line.base},`,
      "        zorder=2,",
    );
    if (spec.marker) out.push('        marker="o",');
    out.push("    )");
  }
  out.push("");
}

function emitScatterDraw(spec: FigureSpec & { kind: "scatter" }, out: string[]): void {
  const preset = PRESETS[spec.style.preset];
  const trend = spec.trendline === "linear";
  out.push("", "def draw(ax, df):");
  if (spec.group) {
    out.push(
      "    names = series_names(df)",
      "    for index, name in enumerate(names):",
      "        frame = df[df[GROUP] == name]",
      "        style = series_style(name, index, len(names))",
      "        ax.scatter(",
      "            frame[X_FIELD],",
      "            frame[Y_FIELD],",
      "            label=str(name),",
      '            color=style["colour"],',
      '            s=style["size"],',
      '            alpha=style["alpha"],',
      '            zorder=style["zorder"],',
      '            marker=style["marker"],',
      "        )",
    );
    if (trend) out.push('        add_trendline(ax, frame[X_FIELD], frame[Y_FIELD], style["colour"])');
  } else {
    out.push(
      `    ax.scatter(df[X_FIELD], df[Y_FIELD], color=PALETTE[0], s=${preset.marker.base}, zorder=2)`,
    );
    if (trend) out.push("    add_trendline(ax, df[X_FIELD], df[Y_FIELD], PALETTE[0])");
  }
  out.push("");
}

function emitBarDraw(spec: FigureSpec & { kind: "bar" }, out: string[]): void {
  const vertical = spec.orientation === "vertical";
  const plot = vertical ? "bar" : "barh";
  const tickAxis = vertical ? "x" : "y";

  out.push("", "def draw(ax, df):", "    frame = aggregate(df)");
  out.push(
    "    categories = list(dict.fromkeys(frame[X_FIELD].tolist()))",
    "    positions = np.arange(len(categories))",
  );

  if (spec.group) {
    out.push(
      "    names = series_names(frame)",
      "    width = 0.8 / max(len(names), 1)",
      "    for index, name in enumerate(names):",
      "        subset = frame[frame[GROUP] == name].set_index(X_FIELD).reindex(categories)",
      "        offset = (index - (len(names) - 1) / 2) * width",
      "        style = series_style(name, index, len(names))",
      `        ax.${plot}(`,
      "            positions + offset,",
      "            subset[Y_FIELD].to_numpy(),",
      "            width,",
      "            label=str(name),",
      '            color=style["colour"],',
      '            alpha=style["alpha"],',
      '            zorder=style["zorder"],',
      "        )",
    );
  } else {
    out.push(
      "    subset = frame.set_index(X_FIELD).reindex(categories)",
      `    ax.${plot}(positions, subset[Y_FIELD].to_numpy(), 0.7, color=PALETTE[0], zorder=2)`,
    );
  }

  out.push(
    `    ax.set_${tickAxis}ticks(positions)`,
    `    ax.set_${tickAxis}ticklabels([str(value) for value in categories])`,
  );
  if (!vertical) {
    out.push(
      "    # barh puts the first category at the bottom; readers expect it at the top.",
      "    ax.invert_yaxis()",
    );
  }
  out.push("");
}

function emitFinish(spec: FigureSpec, out: string[]): void {
  out.push("", "def finish(fig, ax):");

  for (const specAxis of ["x", "y"] as const) {
    const axis = spec[specAxis];
    const target = plotAxis(spec, specAxis);
    out.push(`    ax.set_${target}label(${pyStr(axisLabel(axis))})`);
    if (isCategorical(spec, specAxis)) continue;
    if (axis.scale !== "linear") out.push(`    ax.set_${target}scale(${pyStr(axis.scale)})`);
  }

  if (spec.kind === "bar" && spec.baseline_zero && spec.y.scale !== "log") {
    out.push(
      plotAxis(spec, "y") === "y" ? "    ax.set_ylim(bottom=0)" : "    ax.set_xlim(left=0)",
    );
  }

  for (const specAxis of ["x", "y"] as const) {
    const axis = spec[specAxis];
    if (!axis.limits || isCategorical(spec, specAxis)) continue;
    const target = plotAxis(spec, specAxis);
    out.push(`    ax.set_${target}lim(${axis.limits[0]}, ${axis.limits[1]})`);
  }

  if (spec.title) out.push(`    ax.set_title(${pyStr(spec.title)})`);
  out.push(spec.style.grid ? "    ax.grid(True, linewidth=0.4, alpha=0.5)" : "    ax.grid(False)");

  if (spec.style.despine) {
    out.push('    for side in ("top", "right"):', "        ax.spines[side].set_visible(False)");
  }

  if (spec.group && spec.legend.show) {
    out.push(
      "    ax.legend(",
      `        title=${pyOptStr(spec.legend.title)},`,
      "        frameon=False,",
      `        ${LEGEND_LOCATIONS[spec.legend.position]},`,
    );
    if (spec.legend.position === "outside_bottom") {
      out.push("        ncol=min(len(ax.get_legend_handles_labels()[0]), 4),");
    }
    out.push("    )");
  }

  const outsideLegend =
    spec.group !== undefined &&
    spec.legend.show &&
    (spec.legend.position === "outside_right" || spec.legend.position === "outside_bottom");

  if (outsideLegend) {
    out.push("    # tight_layout is skipped: it fights a legend anchored outside the axes.");
  } else {
    out.push("    fig.tight_layout()");
  }
  out.push("");
}

function emitMain(spec: FigureSpec, out: string[]): void {
  const warns = spec.kind !== "scatter" && spec.aggregation === "none";
  const [targetWidth] = FIGURE_SIZES[spec.output.size];

  out.push(
    "",
    "def metadata_for(fmt):",
    "    # Embedding the spec means a reviewer can recover what produced the figure.",
    '    if fmt == "png":',
    '        return {"Software": TOOL, "Description": SPEC_JSON}',
    '    if fmt == "svg":',
    '        return {"Creator": TOOL, "Description": SPEC_JSON}',
    '    return {"Creator": TOOL, "Subject": SPEC_JSON}',
    "",
    "",
    "def check(fig):",
    "    # Optional. Install graphunslopify for readability and colour checks.",
    "    try:",
    "        from graphunslopify import inspect_figure",
    "    except ImportError:",
    '        print("graphunslopify not installed, skipping figure checks")',
    "        return True",
    `    report = inspect_figure(fig, target_width_in=${targetWidth})`,
    "    print(report)",
    "    return report.ok",
    "",
    "",
    "def main():",
    "    df = load()",
  );
  if (warns) out.push("    warn_duplicates(df)");
  out.push(
    "    with plt.rc_context(RC_PARAMS):",
    "        fig, ax = plt.subplots(figsize=FIGSIZE)",
    "        draw(ax, df)",
    "        finish(fig, ax)",
    "        check(fig)",
    "        for fmt in FORMATS:",
    '            path = f"{STEM}.{fmt}"',
    '            kwargs = {"bbox_inches": "tight", "metadata": metadata_for(fmt)}',
    '            if fmt == "png":',
    '                kwargs["dpi"] = DPI',
    "            fig.savefig(path, **kwargs)",
    '            print(f"wrote {path}")',
    "    plt.close(fig)",
    "    print(DISCLOSURE)",
    "",
    "",
    'if __name__ == "__main__":',
    "    main()",
  );
}

export function emitPython(spec: FigureSpec): string {
  const out: string[] = [];
  emitHeader(spec, out);
  emitLoad(spec, out);
  emitSeriesHelpers(spec, out);

  const aggregation = spec.kind === "scatter" ? "none" : spec.aggregation;
  if (spec.kind !== "scatter") {
    emitAggregate(aggregation, spec, out);
    if (aggregation === "none") emitDuplicateWarning(spec, out);
  }

  if (spec.kind === "scatter" && spec.trendline === "linear") emitTrendline(out);

  if (spec.kind === "line") emitLineDraw(spec, out);
  else if (spec.kind === "scatter") emitScatterDraw(spec, out);
  else emitBarDraw(spec, out);

  emitFinish(spec, out);
  emitMain(spec, out);

  return out.join("\n").replace(/\n{3,}/g, "\n\n\n") + "\n";
}
